# Generated by Django 4.2.8 on 2024-03-21 07:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, verbose_name='Слаг')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('time_cook', models.PositiveIntegerField(default=0, verbose_name='Время готовки')),
                ('portion', models.PositiveIntegerField(default=1, verbose_name='Порций')),
                ('products', models.TextField(max_length=2000, verbose_name='Продукты')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food/%Y/%m', verbose_name='Изображение')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='food', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='food_site.category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True, verbose_name='Лайк')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='food_site.food', verbose_name='Рецепт')),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'ordering': ['food'],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='food_site.subcategory', verbose_name='Субкатегория'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='food_site.food', verbose_name='Рецепт')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='food_site_c_title_d96e09_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['title'], name='food_site_s_title_655267_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['food'], name='food_site_l_food_id_3def91_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user'], name='food_site_l_user_id_b7ed1d_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['-date_created'], name='food_site_f_date_cr_878e44_idx'),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['-date_created'], name='food_site_c_date_cr_f7bf28_idx'),
        ),
    ]
