# Generated by Django 4.2.8 on 2024-03-22 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food/None', verbose_name='')),
                ('text', models.TextField(max_length=1000, verbose_name='')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='food_site.food', verbose_name='')),
            ],
        ),
    ]
