# Generated by Django 4.2.8 on 2024-03-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_site', '0002_stepfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='food_site.food', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='stepfood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food/food_steps/%Y/%d', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='stepfood',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Текст'),
        ),
    ]
