# Generated by Django 4.2.8 on 2024-03-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('country_code', models.CharField(max_length=100, verbose_name='Код')),
                ('value', models.CharField(max_length=20, verbose_name='Курс')),
            ],
        ),
    ]
