# Generated by Django 4.2.8 on 2024-03-10 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_valute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valute',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
