# Generated by Django 4.2.8 on 2024-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_valute', '0002_valute_date_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valute',
            options={'ordering': ['country_code']},
        ),
        migrations.AlterField(
            model_name='valute',
            name='date_update',
            field=models.DateField(verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='valute',
            index=models.Index(fields=['country_code'], name='course_valu_country_69cf83_idx'),
        ),
    ]
