# Generated by Django 4.2.8 on 2024-03-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/img/user.png', null=True, upload_to='user/%Y/%m/%d'),
        ),
    ]
