# Generated by Django 4.2.8 on 2024-03-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='img/user.png', null=True, upload_to='user/%Y/%m/%d'),
        ),
    ]
